# Analyse des données d'entraînement / validation

### Chargement d'un fichier csv

In [3]:
from textmine.utils import read_dataframe

df = read_dataframe("../resources/train.csv")

In [4]:
df

,text,entities,relations,predictions
id,,,,
181,"Anam Destresse, président de l'ONG ""Ma passion...",[id=0 type='ACCIDENT' mentions=[Mention(value=...,"[[0, STARTED_IN, 9], [7, IS_LOCATED_IN, 9], [5...","[[5, IS_COOPERATING_WITH, 14], [8, OPERATES_IN..."
31669,"À Paris, le 8 avril 2022, l'usine de déodorant...",[id=0 type='CBRN_EVENT' mentions=[Mention(valu...,"[[9, IS_LOCATED_IN, 8], [11, OPERATES_IN, 8], ...",NaN
51470,"En Espagne, dans une région agricole, une cont...",[id=0 type='POLLUTION' mentions=[Mention(value...,"[[7, IS_PART_OF, 8], [9, OPERATES_IN, 1], [0, ...",NaN
51332,Un important incendie a fait des ravages dans ...,[id=0 type='FIRE' mentions=[Mention(value='inc...,"[[12, IS_IN_CONTACT_WITH, 5], [0, IS_LOCATED_I...",NaN
1131,« Je coule » : onze heures après avoir envoyé ...,[id=0 type='ACCIDENT' mentions=[Mention(value=...,"[[9, IS_LOCATED_IN, 2], [0, START_DATE, 17], [...","[[2, IS_LOCATED_IN, 3], [4, GENDER_FEMALE, 4],..."
...,...,...,...,...
1288,"M. Thibault Alekseï, membre de l'association ""...",[id=0 type='ACCIDENT' mentions=[Mention(value=...,"[[2, IS_PART_OF, 3], [12, IS_IN_CONTACT_WITH, ...",NaN
3822,Des employés d'une usine de production médical...,[id=0 type='STRIKE' mentions=[Mention(value='g...,"[[8, HAS_CONTROL_OVER, 7], [4, HAS_CATEGORY, 1...",NaN
51266,"Le 13 mars 2001, Belgrade a connu un krach bou...",[id=0 type='ECONOMICAL_CRISIS' mentions=[Menti...,"[[1, STARTED_IN, 3], [10, IS_PART_OF, 4], [2, ...",NaN
51368,"L'incendie du laboratoire ""FileGen"" a eu lieu ...",[id=0 type='FIRE' mentions=[Mention(value='inc...,"[[1, HAS_CONTROL_OVER, 3], [7, IS_LOCATED_IN, ...",NaN
124,L’avion NY8 de la compagnie Airîle a lancé sa ...,[id=0 type='ACCIDENT' mentions=[Mention(value=...,"[[14, HAS_CATEGORY, 22], [10, OPERATES_IN, 8],...",NaN

### Récupérer un document par son identifiant

In [5]:
sample = df.loc[181]
print(sample.text)

Anam Destresse, président de l'ONG "Ma passion", a été blessé dans un accident. Le 30 juin 2022, un accident de circulation s'est produit entre une moto et un bus sur l'autoroute de Saint-Marin en Italie. Le bus, qui transportait 20 passagers, appartenait à l'ONG. Lors de l'accident, les panneaux de signalisation ont été complètement endommagés et le garde du corps a été blessé. Au total, deux passagers sont morts sur le coup. Anam Destresse, qui faisait partie des blessés, a été transporté en hélicoptère jusqu'à l'hôpital. Le conducteur de la moto a été retrouvé mort en dessous du bus. Il conduisait sans permis et en état d'ivresse.

In [6]:
sample.entities

[Entity(id=0, type='ACCIDENT', mentions=[Mention(value='accident', start=70, end=78), Mention(value='accident de circulation', start=100, end=123), Mention(value='accident', start=275, end=283)]),
 Entity(id=1, type='CIVILIAN', mentions=[Mention(value='Anam Destresse', start=0, end=14), Mention(value='Anam Destresse', start=431, end=445)]),
 Entity(id=2, type='MATERIEL', mentions=[Mention(value='moto', start=148, end=152), Mention(value='moto', start=550, end=554)]),
 Entity(id=3, type='MATERIEL', mentions=[Mention(value='bus', start=159, end=162), Mention(value='bus', start=208, end=211), Mention(value='bus', start=589, end=592)]),
 Entity(id=4, type='MATERIEL', mentions=[Mention(value='panneaux de signalisation', start=289, end=314)]),
 Entity(id=5, type='GROUP_OF_INDIVIDUALS', mentions=[Mention(value='blessés', start=470, end=477)]),
 Entity(id=6, type='MATERIEL', mentions=[Mention(value='hélicoptère', start=499, end=510)]),
 Entity(id=7, type='CIVILIAN', mentions=[Mention(value='garde du corps', start=353, end=367)]),
 Entity(id=8, type='NON_GOVERNMENTAL_ORGANISATION', mentions=[Mention(value='Ma passion', start=36, end=46), Mention(value='ONG', start=260, end=263)]),
 Entity(id=9, type='PLACE', mentions=[Mention(value='autoroute de Saint-Marin', start=169, end=193)]),
 Entity(id=10, type='PLACE', mentions=[Mention(value='Italie', start=197, end=203)]),
 Entity(id=11, type='PLACE', mentions=[Mention(value='hôpital', start=521, end=528)]),
 Entity(id=12, type='GROUP_OF_INDIVIDUALS', mentions=[Mention(value='passagers', start=233, end=242)]),
 Entity(id=13, type='GROUP_OF_INDIVIDUALS', mentions=[Mention(value='passagers', start=397, end=406)]),
 Entity(id=14, type='TERRORIST_OR_CRIMINAL', mentions=[Mention(value='conducteur', start=533, end=543), Mention(value='Il', start=594, end=596)]),
 Entity(id=15, type='TIME_EXACT', mentions=[Mention(value='30 juin 2022', start=83, end=95)]),
 Entity(id=16, type='FIRSTNAME', mentions=[Mention(value='Anam', start=0, end=4)]),
 Entity(id=17, type='LASTNAME', mentions=[Mention(value='Destresse', start=5, end=14)]),
 Entity(id=18, type='CATEGORY', mentions=[Mention(value='président', start=16, end=25)]),
 Entity(id=19, type='CATEGORY', mentions=[Mention(value='garde du corps', start=353, end=367)]),
 Entity(id=20, type='CATEGORY', mentions=[Mention(value='conducteur', start=533, end=543)]),
 Entity(id=21, type='QUANTITY_EXACT', mentions=[Mention(value='deux', start=392, end=396)]),
 Entity(id=22, type='QUANTITY_EXACT', mentions=[Mention(value='20', start=230, end=232)]),
 Entity(id=23, type='FIRSTNAME', mentions=[Mention(value='Anam', start=431, end=435)]),
 Entity(id=24, type='LASTNAME', mentions=[Mention(value='Destresse', start=436, end=445)])]

In [7]:
sample.relations

[[0, 'STARTED_IN', 9],
 [7, 'IS_LOCATED_IN', 9],
 [5, 'IS_LOCATED_IN', 10],
 [1, 'GENDER_FEMALE', 1],
 [12, 'IS_LOCATED_IN', 10],
 [0, 'IS_LOCATED_IN', 10],
 [1, 'IS_LOCATED_IN', 10],
 [13, 'IS_LOCATED_IN', 9],
 [14, 'IS_LOCATED_IN', 10],
 [1, 'HAS_CATEGORY', 18],
 [5, 'IS_LOCATED_IN', 9],
 [9, 'IS_LOCATED_IN', 10],
 [14, 'IS_DEAD_ON', 15],
 [7, 'HAS_CATEGORY', 19],
 [12, 'IS_LOCATED_IN', 9],
 [0, 'IS_LOCATED_IN', 9],
 [7, 'GENDER_MALE', 7],
 [11, 'IS_LOCATED_IN', 10],
 [1, 'IS_LOCATED_IN', 9],
 [14, 'IS_LOCATED_IN', 9],
 [14, 'HAS_CATEGORY', 20],
 [0, 'STARTED_IN', 10],
 [0, 'START_DATE', 15],
 [7, 'IS_LOCATED_IN', 10],
 [0, 'END_DATE', 15],
 [14, 'GENDER_MALE', 14],
 [12, 'IS_OF_SIZE', 22],
 [13, 'IS_LOCATED_IN', 10],
 [1, 'IS_LOCATED_IN', 11],
 [13, 'IS_OF_SIZE', 21]]

In [8]:
sample.predictions

[[5, 'IS_COOPERATING_WITH', 14],
 [8, 'OPERATES_IN', 11],
 [5, 'IS_AT_ODDS_WITH', 1],
 [4, 'HAS_QUANTITY', 21],
 [1, 'HAS_FAMILY_RELATIONSHIP', 7],
 [12, 'HAS_CONTROL_OVER', 3],
 [3, 'HAS_QUANTITY', 22],
 [1, 'HAS_CONTROL_OVER', 12],
 [5, 'IS_COOPERATING_WITH', 7],
 [13, 'CREATED', 12],
 [7, 'CREATED', 5],
 [7, 'IS_AT_ODDS_WITH', 12],
 [12, 'IS_AT_ODDS_WITH', 8],
 [14, 'HAS_CONTROL_OVER', 2],
 [1, 'HAS_CONTROL_OVER', 5],
 [12, 'HAS_CONTROL_OVER', 5],
 [1, 'IS_AT_ODDS_WITH', 8],
 [12, 'CREATED', 13],
 [13, 'WAS_CREATED_IN', 15],
 [8, 'IS_AT_ODDS_WITH', 13],
 [12, 'IS_PART_OF', 13],
 [13, 'CREATED', 5],
 [14, 'HAS_CATEGORY', 20],
 [14, 'GENDER_MALE', 14],
 [1, 'IS_COOPERATING_WITH', 5],
 [13, 'IS_AT_ODDS_WITH', 12],
 [7, 'IS_AT_ODDS_WITH', 5],
 [5, 'OPERATES_IN', 10],
 [12, 'IS_AT_ODDS_WITH', 1],
 [7, 'IS_AT_ODDS_WITH', 14],
 [14, 'CREATED', 12],
 [5, 'IS_IN_CONTACT_WITH', 12],
 [1, 'CREATED', 5],
 [13, 'IS_AT_ODDS_WITH', 5],
 [13, 'IS_AT_ODDS_WITH', 14],
 [0, 'INJURED_NUMBER', 22],
 [5, 'IS_LOCATED_IN', 11],
 [14, 'CREATED', 5],
 [1, 'IS_IN_CONTACT_WITH', 5],
 [7, 'HAS_CATEGORY', 19],
 [14, 'IS_AT_ODDS_WITH', 12],
 [5, 'IS_COOPERATING_WITH', 13],
 [8, 'OPERATES_IN', 10],
 [5, 'WAS_CREATED_IN', 15],
 [5, 'IS_IN_CONTACT_WITH', 14],
 [13, 'OPERATES_IN', 9],
 [5, 'IS_AT_ODDS_WITH', 12],
 [8, 'IS_COOPERATING_WITH', 5],
 [7, 'IS_IN_CONTACT_WITH', 5],
 [0, 'END_DATE', 15],
 [14, 'IS_AT_ODDS_WITH', 5],
 [12, 'OPERATES_IN', 10],
 [8, 'IS_AT_ODDS_WITH', 1],
 [5, 'IS_IN_CONTACT_WITH', 7],
 [13, 'HAS_CONTROL_OVER', 6],
 [13, 'OPERATES_IN', 11],
 [5, 'IS_AT_ODDS_WITH', 14],
 [0, 'IS_LOCATED_IN', 10],
 [14, 'IS_AT_ODDS_WITH', 7],
 [1, 'IS_LOCATED_IN', 11],
 [12, 'IS_AT_ODDS_WITH', 13],
 [5, 'IS_AT_ODDS_WITH', 7],
 [5, 'OPERATES_IN', 9],
 [12, 'WAS_CREATED_IN', 15],
 [0, 'DEATHS_NUMBER', 21],
 [7, 'IS_AT_ODDS_WITH', 13],
 [1, 'IS_BORN_IN', 11],
 [12, 'CREATED', 5],
 [1, 'RESIDES_IN', 11],
 [5, 'IS_COOPERATING_WITH', 1],
 [1, 'IS_AT_ODDS_WITH', 12],
 [14, 'HAS_CONTROL_OVER', 6],
 [14, 'IS_IN_CONTACT_WITH', 5],
 [14, 'IS_DEAD_ON', 15],
 [5, 'OPERATES_IN', 11],
 [1, 'IS_AT_ODDS_WITH', 5],
 [12, 'IS_AT_ODDS_WITH', 5],
 [1, 'HAS_CONTROL_OVER', 11],
 [1, 'IS_AT_ODDS_WITH', 14],
 [12, 'IS_AT_ODDS_WITH', 14],
 [14, 'DIED_IN', 0],
 [5, 'IS_IN_CONTACT_WITH', 13],
 [13, 'HAS_CONTROL_OVER', 3],
 [7, 'HAS_CONTROL_OVER', 5],
 [7, 'IS_AT_ODDS_WITH', 8],
 [1, 'INITIATED', 0],
 [1, 'IS_AT_ODDS_WITH', 7],
 [12, 'OPERATES_IN', 9],
 [1, 'HAS_CONTROL_OVER', 13],
 [14, 'IS_AT_ODDS_WITH', 13],
 [7, 'IS_COOPERATING_WITH', 5],
 [8, 'IS_AT_ODDS_WITH', 12],
 [13, 'HAS_CONTROL_OVER', 5],
 [13, 'IS_AT_ODDS_WITH', 8],
 [13, 'OPERATES_IN', 10],
 [5, 'HAS_CONTROL_OVER', 1],
 [7, 'IS_AT_ODDS_WITH', 1],
 [5, 'IS_AT_ODDS_WITH', 13],
 [1, 'HAS_CONTROL_OVER', 6],
 [12, 'HAS_CONTROL_OVER', 6],
 [12, 'OPERATES_IN', 11],
 [1, 'IS_IN_CONTACT_WITH', 8],
 [12, 'IS_IN_CONTACT_WITH', 5],
 [5, 'IS_IN_CONTACT_WITH', 8],
 [8, 'IS_AT_ODDS_WITH', 5],
 [7, 'HAS_FAMILY_RELATIONSHIP', 1],
 [13, 'IS_AT_ODDS_WITH', 1],
 [8, 'IS_AT_ODDS_WITH', 14],
 [0, 'START_DATE', 15],
 [0, 'INJURED_NUMBER', 21],
 [14, 'IS_AT_ODDS_WITH', 8],
 [14, 'HAS_CONTROL_OVER', 5],
 [13, 'IS_PART_OF', 12],
 [5, 'IS_IN_CONTACT_WITH', 1],
 [14, 'CREATED', 13],
 [5, 'IS_COOPERATING_WITH', 12],
 [8, 'OPERATES_IN', 9],
 [5, 'IS_AT_ODDS_WITH', 8],
 [13, 'IS_IN_CONTACT_WITH', 5],
 [1, 'HAS_FAMILY_RELATIONSHIP', 14],
 [8, 'IS_COOPERATING_WITH', 1],
 [14, 'IS_AT_ODDS_WITH', 1],
 [2, 'HAS_QUANTITY', 21],
 [1, 'IS_AT_ODDS_WITH', 13]]